name: build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Config
        run: |
          echo "DEV_DIR=./.dev" >> $GITHUB_ENV

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "GITHUB_TAGNAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi
        shell: bash
      -
        name: Checkout dev
        uses: actions/checkout@v2
        with:
          repository: neard/dev
          path: ${{ env.DEV_DIR }}
      -
        name: Build
        run: |
          ant release -Ddev.dir=${{ env.DEV_DIR }}
        shell: bash
        env:
          GITHUB_TAGNAME: ${{ env.GITHUB_TAGNAME }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
      -
        name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: bin/releases/*
      -
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            bin/releases/*
          name: ${{ env.GITHUB_TAGNAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v1
